### ISSUE TITLE
Authorization Token已过期，请重新生成/获取

### ISSUE THREAD

**Issue by necromancer1** [zhipuai/zhipuai-sdk-python-v4#8]
在个人实名后，生成API key，SDK调用报如下错误：

APIAuthenticationError('Error code: 401, with error text {"error":{"code":"1003","message":"Authorization Token已过期，请重新生成/获取。"}}')

重新生成API key，依然报401错误。

**Comment by TravisRoad** [comment]
你好，我遇到了相同的问题，请问你是如何解决的呢
